---
- hosts: all
  become: yes
  become_method: runas
  become_user: SYSTEM

  roles:
    - ncpa_install_windows

- hosts: all
  remote_user: root
  roles:
    - register_with_xi
    - xi_apply_config
