---
- name: Install NCPA on Windows
  hosts: windows
  become: yes
  become_method: runas
  become_user: SYSTEM

  roles:
    - ncpa_install_windows

- name: Register Windows host and services
  hosts: windows

  roles:
    - register_host_with_xi
    - register_cpu_service_with_xi
    - register_ram_service_with_xi
    - register_windows_disk_service_with_xi
    - xi_apply_config
