---
- name: apply configs
  hosts: all
  tasks:
    - uri:
        url: http://{{ xi_ip }}/nagiosxi/api/v1/config/host?apikey={{ xi_api_key }}
        body: "force=1&applyconfig=1"
        method: POST
        validate_certs: no
        timeout: 120
      delegate_to: 127.0.0.1
      run_once: true