---
- name: register service NCPA swap
  hosts: all
  connection: ssh
  gather_facts: True
  remote_user: root
  tasks:

    - uri:
        url: http://{{ xi_ip }}/nagiosxi/api/v1/config/service?apikey={{ xi_api_key }}
        body: "host_name={{ ansible_default_ipv4.address }}&service_description=swap&check_command=check_xi_ncpa\\!-t '{{ token }}' -P 5693 -M memory/swap -u -w 50 -c 80&check_interval=5&retry_interval=1&max_check_attempts=2&check_period=24x7&contacts=nagiosadmin&notification_interval=5&notification_period=24x7"
        method: POST
        validate_certs: no
        timeout: 120