---
- name: NCPA Install
  # ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook -i [HOSTFILE] ncpa.yml --extra-vars " token=[NEWTOKEN] "
  hosts: 192.168.3.203
  connection: ssh
  gather_facts: True
  tasks:
    - name: Download NCPA (Debian)
      get_url: url=https://assets.nagios.com/downloads/ncpa/ncpa-latest.d9.amd64.deb dest=/tmp/ncpa.deb
      when: ansible_os_family == "Debian"
    - name: Download NCPA (RedHat)
      get_url: url=https://assets.nagios.com/downloads/ncpa/ncpa-latest.el6.x86_64.rpm dest=/tmp/ncpa.rpm
      when: ansible_os_family == "RedHat"
    - name: Install package (Debian)
      package:
        name: /tmp/ncpa.deb
        state: present
      when: ansible_os_family == "Debian"
    - name: Install package (RedHat)
      package:
        name: /tmp/ncpa.rpm
        state: present
      when: ansible_os_family == "RedHat"
    - name: Change token (RedHat)
      lineinfile:
        dest: /usr/local/ncpa/etc/ncpa.cfg
        regexp: ^community_string
        line: "community_string = {{ token }}"
      when: ansible_os_family == "RedHat"
    - name: Change token (Debian)
      lineinfile:
        dest: /etc/ncpa/ncpa.cfg
        regexp: ^community_string
        line: "community_string = {{ token }}"
      when: ansible_os_family == "Debian"
    - name: Start NCPA
      service:
        name: ncpa_listener
        state: started
        enabled: yes
...