---
- name: RedHat install policycoreutils for SELinux using non-standard syslog port
  yum:
    name: policycoreutils
    state: present
  when: ansible_selinux is defined and ansible_selinux != False and ansible_selinux.status == 'enabled' and ansible_os_family == "RedHat"

- name: RedHat install setroubleshoot for SELinux using non-standard syslog port
  yum:
    name: setroubleshoot
    state: present
  when: ansible_selinux is defined and ansible_selinux != False and ansible_selinux.status == 'enabled' and ansible_os_family == "RedHat"
  
- name: Ubuntu install semanage-utils
  apt:
    name: semanage-utils
    state: present
  when: ansible_selinux is defined and ansible_selinux != False and ansible_distribution == "Ubuntu"
  
- name: Ubuntu install python-selinux
  apt:
    name: python-selinux
    state: present
  when: ansible_selinux is defined and ansible_selinux != False and ansible_distribution == "Ubuntu"

- name: Ubuntu install python-semanage
  apt:
    name: python-semanage
    state: present
  when: ansible_selinux is defined and ansible_selinux != False and ansible_distribution == "Ubuntu"  
  
- name: selinux allow rsyslog export through non-standard port
  command: semanage port -a -t syslogd_port_t -p tcp 5544
  when: ansible_selinux is defined and ansible_selinux != False