---
- name: Forward Linux syslog to Nagios Log Server
  remote_user: root
  hosts: all
  
  roles:
    - selinux
    - download_linux_setup
    - linux_base_setup
    - linux_apacheAccessLog_setup
    - linux_apacheErrorLog_setup
    - linux_mysqlLog_setup